project:
  type: website

website:
  title: "Make your research FAIRer"
  favicon: assets/SIB_logo.svg
  search: true
  page-navigation: true
  repo-url: "https://github.com/sib-swiss/reproducible-analysis-training"
  repo-actions: [edit, issue]
  site-url: "https://sib-swiss.github.io/reproducible-analysis-training/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - course_preparations.qmd
      - slides.qmd
      - text: Exercises
        menu:
        - href: exercises_quarto.qmd
        - href: exercises_git.qmd
        - href: exercises_zenodo.qmd
        
    right:
      - icon: github
        href: "https://github.com/sib-swiss/reproducible-analysis-training"
        aria-label: GitHub
  sidebar:
    logo: assets/SIB_LogoQ_GBv.svg

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
