project:
  type: website

website:
  title: "Make your research FAIRer"
  repo-url: "https://github.com/sib-swiss/reproducible-analysis"
  repo-actions: [edit, issue]
  site-url: "https://sib-swiss.github.io/reproducible-analysis/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - course_preparations.qmd
      - slides.qmd
      - text: Exercises
        menu:
        - href: exercises_quarto.qmd
        - href: exercises_git.qmd
        - href: exercises_zenodo.qmd
        
    right:
      - icon: github
        href: "https://github.com/sib-swiss/reproducible-analysis"
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
